service: chickenfreshoutthekitchen

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-offline

# Configuration for serverless-webpack
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  environment:
      LOCATION_ID: ${file(secret.json):LOCATION_ID}
      SQUARE_SECRET: ${file(secret.json):SQUARE_SECRET}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - 'dynamodb:*'
      Resource: "arn:aws:dynamodb:us-east-1:050463389957:table/chickenfreshoutthekitchen_finished_orders"
    - Effect: "Allow"
      Action:
        - 'iot:*'
      Resource: "*"
    - Effect: "Allow"
      Action:
        - 'sts:AssumeRole'
      Resource: "*"

functions:
  getAdminPanel:
    handler: handler.getAdminPanel
    events:
      - http: GET admin_panel
  handleWebhooks:
    handler: handler.handleWebhooks
    events:
      - http: POST webhook
  auth:
    handler: handler.auth
    events:
      - http:
          method: GET
          path: iot/keys
          cors: true
    memorySize: 128
    timeout: 10
